[package]
name = "touying-criterion"
version = "0.1.0"
compiler = "0.13.1"
entrypoint = "lib.typ"
authors = ["thy0s <https://github.com/thy0s>"]
license = "MIT"
description = "A basic slide template for a variety of different purposes."
repository = "https://github.com/thy0s/touying-criterion"
keywords = ["presentation", "touying", "slides", "education", "business", "computer science", "lecture", "clean"]
categories = ["presentation"]
disciplines = ["business", "education", "computer-science",]
exclude = [".gitignore"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"